### ISSUE TITLE
Metafeatures for attributes

### ISSUE THREAD

**Issue by jaksmid** [openml/OpenML#112]
Current schema of openML allows to extract metafeatures that characterizes the dataset as a whole or that aggregates data from individual attributes. It is currently impossible to add metafeatures that describe each attribute separately.

For example, for a dataset with two numerical attributes, metafeatures like average of the first attribute and average of the second attribute should be allowed to be extracted.

**Comment by joaquinvanschoren** [comment]
@jaksmid I believe you worked on this during one of the earlier hackathons? Can you give an update?

**Comment by janvanrijn** [comment]
The API support is there (since a year)

People can write their own evaluation engines and upload both dataset based and feature based meta-features. I will write an update of the evaluation engine that uploads skewness per attribute etc. 

Note that @WilliamRaynaut and @jaksmid also worked on this feature (Munich 2017 workshop)

**Comment by janvanrijn** [comment]
Will close this for now
