### ISSUE TITLE
Potential problem / question regarding impl. ids

### ISSUE THREAD

**Issue by berndbischl** [openml/OpenML#14]
They way I understand it:
Impl ID = name + version (Both user chosen)

When uploading, the server tells me, whether this combo is already in use and therefore not possible. 

Could  we please specify somewhere in the docs what chars are actually allowed for id and version? Do we really allow:
name = "Jörg's cool algorithm^2" ?

**Comment by mfeurer** [comment]
Is there a reason why brackets in flow names are forbidden? My use case is that I want to store a pipeline in scikit-learn, and want to add the components to the name of the flow to distinguish between similar pipelines, for example:

* sklearn.grid_search.RandomizedSearchCV(sklearn.pipeline.Pipeline(sklearn.preprocessing.data.StandardScaler,sklearn.pipeline.FeatureUnion(sklearn.preprocessing.data.PolynomialFeatures,sklearn.decomposition.pca.PCA),sklearn.ensemble.weight_boosting.AdaBoostClassifier(sklearn.tree.tree.DecisionTreeClassifier)))
* sklearn.grid_search.RandomizedSearchCV(sklearn.pipeline.Pipeline(sklearn.preprocessing.data.StandardScaler,sklearn.pipeline.FeatureUnion(sklearn.preprocessing.data.PolynomialFeatures,sklearn.decomposition.pca.PCA),sklearn.ensemble.weight_boosting.RandomForestClassifier))

I want to use brackets here instead of the underscores as done for WEKA, because the flows contains nested components.

**Comment by janvanrijn** [comment]
I updated XSD, ( and ) are now possible

**Comment by mfeurer** [comment]
Thanks for your fast reply. I just tried this on the test server, it still works with plain strings like `dummy`, but not with complicated strings as shown above.

**Comment by joaquinvanschoren** [comment]
Jan, did you perhaps only push the change to the production server?

**Comment by mfeurer** [comment]
@joaquinvanschoren @janvanrijn are there any news on this?

**Comment by janvanrijn** [comment]
Yes, I pushed this to the production server. 

Now also on test server.

**Comment by mfeurer** [comment]
It works now, thanks a lot

**Comment by mfeurer** [comment]
Sorry to open this again, but could you please also allow commas to be part of the name?

**Comment by janvanrijn** [comment]
Not so sure actually. As flow names are defined to be URL safe, according to HTTP specification comma's can not occur in a URL. 

Need to check many things internally before being able to change this

**Comment by mfeurer** [comment]
I didn't know that. I'll think about a different solution.

**Comment by janvanrijn** [comment]
The answer wasn't a "no"!

It was more a "definitely not now"

**Comment by mfeurer** [comment]
Sure, but I need a solution as soon as possible, it didn't sound like 'not now' is before the 10th of May ;)

**Comment by mfeurer** [comment]
Brackets are actually working now.
