### ISSUE TITLE
Listing tasks and data sets API calls should include dset name

### ISSUE THREAD

**Issue by berndbischl** [openml/OpenML#168]
The data set name must be included in the output

**Comment by berndbischl** [comment]
I also want some info on resampling used

**Comment by berndbischl** [comment]
I also want (also in the data set charactersitics) some info on size of largest class compared to smallest one

**Comment by berndbischl** [comment]
For listing data sets it would be nice to see the datatype (eg categorical or real) for the default target feature.

**Comment by berndbischl** [comment]
for tasks (and probably data sets) we have NumberOfNumericFeatures. Numbers for other feature types are also good!

**Comment by joaquinvanschoren** [comment]
done, leaving open until documented

**Comment by joaquinvanschoren** [comment]
Right now we have a did and (dataset) 'name' field for each task. This will get messy for tasks with more than one input dataset.  Is it ok if we gradually *remove* did and name fields, and you use the values of the 'source_data' input?  You can still extract them easily from there, and it will keep working if there are multiple input datasets. Also, we should add the name of the evaluation procedure instead of just the id.

**Comment by joaquinvanschoren** [comment]
Done:
http://www.openml.org/api_docs/#!/data/get_data_list
http://www.openml.org/api_docs/#!/task/get_task_list
