### ISSUE TITLE
Sense of row ID attributes

### ISSUE THREAD

**Issue by dominikkirchhoff** [openml/OpenML#178]
Hi,

in [data set 377](http://openml.liacs.nl/d/377) (synthetic_control), there's a row ID attribute called "index" going from 1 to 600. [Task 3512](http://openml.liacs.nl/t/3512) uses this data set, but the corresponding data splits are 0-based, i.e., do not take the row ID attribute into account. Now I don't really get the sense of the attribute then, because I would expect the data splits to range from 1 to 600 as well.

**Comment by joaquinvanschoren** [comment]
Hi dominik, this attribute was in the dataset uploaded to OpenML. However,
OpenML simply disregards it and uses its own row numbers. This is exactly
to avoid issues with user-defined row id's. They can be 0-based, 1-based,
or whatever other identifier. Sometimes they are not even numbers. We keep
the features because quite possibly they have some meaning in their domain,
but we flag them because they should not be modelled.

Does that help?

Cheers,
Joaquin

**Comment by dominikkirchhoff** [comment]
All right. That was helpful, thank you!
