### ISSUE TITLE
Name change of user does not effect old runs

### ISSUE THREAD

**Issue by jakob-r** [openml/OpenML#188]
Maybe it's a website issue but I guess it's more the result of a sub optimal normalized database structure.
My old username was "Jakob" and I changed it to my full name.
The result is that old runs show up with my old name http://openml.org/t/12
I guess you save the name with each run whereas only the user id would be necessary which could be matched later if needed,

**Comment by joaquinvanschoren** [comment]
No, this is a website issue, not a database issue. You should get the
correct value from the API.

The website operates on an index because this is faster and puts less
stress on the database. Currently, we don't update the run indices when a
user changes his name, but they will be automatically updated on the next
index rebuild. Still, I will add a rule to update the run index, so that
these changes are immediately visible.

Thanks!
Joaquin

**Comment by joaquinvanschoren** [comment]
Solved a long time ago by reindexing
