### ISSUE TITLE
multiple estimation procedures 

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#336]
This is strange, the `estimationprocedure/list` API returns 

```
   est.id                              name
1       1           10-fold Crossvalidation
2       2    5 times 2-fold Crossvalidation
3       3  10 times 10-fold Crossvalidation
4       4                     Leave one out
5       5                   10% Holdout set
6       6                   33% Holdout set
7       7           10-fold Crossvalidation
8       8    5 times 2-fold Crossvalidation
9       9  10 times 10-fold Crossvalidation
10     10                     Leave one out
11     11                   10% Holdout set
12     12                   33% Holdout set
13     13            10-fold Learning Curve
14     14   10 times 10-fold Learning Curve
15     15       Interleaved Test then Train
16     16                    Custom Holdout
17     17               50 times Clustering
18     18                 Holdout unlabeled
19     19           10-fold Crossvalidation
20     20    5 times 2-fold Crossvalidation
21     21  10 times 10-fold Crossvalidation
22     22                     Leave one out
23     23 100 times 10-fold Crossvalidation
24     24    Custom 10-fold Crossvalidation
25     25            4-fold Crossvalidation
```

It seems that, for example, `Leave one out` has three IDs: 4, 10, 22 . Why do we need this?

**Comment by janvanrijn** [comment]
This is not a(n OpenML) bug. The evaluation list shows entries like this:
`<oml:estimationprocedure>
  <oml:id>1</oml:id>
  <oml:ttid>1</oml:ttid>
  <oml:name>10-fold Crossvalidation</oml:name>
  <oml:type>crossvalidation</oml:type>
  <oml:repeats>1</oml:repeats><oml:folds>10</oml:folds>
  <oml:stratified_sampling>true</oml:stratified_sampling>
</oml:estimationprocedure>`
Some entries are not applicable to certain tasks (e.g., cross-validation on data streams is wrong). In order to make the system only allow legal tasks, the entries of this table are linked to a certain task type (ttid). We currently have leave one out procedures for supervised classification, supervised regression and survival analysis.

**Comment by giuseppec** [comment]
ok, solved.
