### ISSUE TITLE
Studies and tags with "study_X"

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#339]
Suggestion:
- tagging of runs/flows/datasets/tasks with the string "study_X" should only be allowed if there is already a study available in http://www.openml.org/search?type=study that uses the integer X.
- for now, maybe only the user that created the study via http://www.openml.org/new/study should be allowed to use the "study_X" tag, e.g. he should be the "admin" of this study to avoid that other users misuse the tag. Later, we could let the admin decide if other users can add runs to this study (maybe by tagging the user profile with "study_X"?)

**Comment by janvanrijn** [comment]
I party agree. The problem that you identify already bothers me already for a long time and should be fixed thoroughly. The current way that studies are implemented seems a bit indistinct. It complicates the semantic meaning of tags and studies and makes the code more complex. 
- The global semantic meaning of a tag on the internet seems to be "free form of string information adding additional information". On Openml, this is since we implemented studies no longer the case. When I attach a label "study_X" to a dataset, tag, etc, it now has additional meaning. For us (the developers) it is pretty clear what it means, but in general people will not know this and they might by accident extend existing studies, whereas they didn't mean to. (The fact that we're way behind on documenting adds even more to the potential confusion). 
- For semantic reasons, I don't like the idea of restricting users to use certain tags. For example, if I want to tag something with the tag "my_cool_study_about_streams", this should be semantically the same as the tag "study_1" (even though OpenML currently tries to add meaning to the latter tag)
- However, there is also good news. The current tagging system records which users placed which tags at which moment. This gives us a lot of tools to strongly define a study.

This is how I propose to define a study: 
- A study is a collection of entities that tagged by a set of tags defined by the user. This is currently also the case in a very non-flexible way, i.e., the set of tags has size one, this is in fact tag "study_X".
- We will extend this in such a way that the user can define a set of tags that defines such study. By default, it will be just the tag "study_X", but he can also add others (or remove them).
- Tagging returns to it's original concept. Everyone can tag everything with any tag, no restrictions. 
- For each tag that is defined, the owner can set specific restrictions on the entities that are included. He can for example define that entities tagged with "study_X" are only included in the study if they were tagged by him, or a set of friends. Or he can specify that entities tagged with a given tag are only included if they were tagged after a certain date, or before a certain date. 

This way, we add a lot of flexibility to the system and remove a lot of semantic complexity. For end users and workbenches, nothing changes. They still tag their studies with the tag "study_X", unless the owner of the study changed the defaults. This option is easy to implement, and possible to extend later on.

**Comment by janvanrijn** [comment]
The api now contains two additional (undocumented, beta) functions, that display information about studies:
- http://www.openml.org/api/v1/study/list (list of all visible studies)
- http://www.openml.org/api/v1/study/id (shows all entities of a given study)
- (or: http://www.openml.org/api/v1/study/id/data, shows just the datasets of a given study)

which entities to be included in a study, is now defined by the database table "study_tag". Here, we maintain for each study a list of tags that include entities in the study. For example, study 14 contains the tag "study_14", everyone that tags an entity with this tag adds this entity to the study. (So far, all is the same).

However, the creator of the study can further specify the restrictions imposed on such tags. He can define a window_start (only entities that are tagged after a given date will be included), a window_end (only entities tagged before a given date will be included) and a write access level (determining whether only entities tagged by himself, his circle will be included..) 

For all current studies, nothing changes. The tags are open for everyone, and there is no time window selected. Newly created studies are more restricted. They can only be extended by the "creator", and will only include entities tagged after the creation. (say, if someone by accident tagged some entities with study_X before the task actually exists, these will not be included. ) There is currently no user interface for changing this except Phpmyadmin, so email me if you want something changed for a study. I will implement this soon. 

(Future work) he will also be able to extend the tag mapping of his study. ATM, each study is linked to only one tag (tag: study_X). However, maybe someone wants to extend another study (study_Y). He then just adds the tag study_Y to the tag_mapping of his study_X, and everything that is tagged by study_Y or study_X is included in the study. 

@joaquinvanschoren has agreed to implement this in Elastic search. That is, elastic search should use more advanced queries to select entities for a given study. SQL queries to obtain included entities:
https://github.com/openml/website/blob/master/openml_OS/models/Study_tag.php
Also, whenever someone adds a tag to the tag mapping of a study, the study index should be created again.

**Comment by janvanrijn** [comment]
Todo's to close this one: 
@janvanrijn summarize this topic in wiki item
@joaquinvanschoren adapt elastic search so it coops with this new design

**Comment by janvanrijn** [comment]
1) Agreed. I created the code, will be made available with the next PR.
2) That should work, use 'tasks', 'flows', 'setups' or 'runs' (should still document this)
3) Agreed.

**Comment by janvanrijn** [comment]
This discussion has been superseded by the new study model:
docs.openml.org/benchmark
