### ISSUE TITLE
CSV interface unclear

### ISSUE THREAD

**Issue by amueller** [openml/OpenML#507]
I'm trying to download https://www.openml.org/d/310 with the CSV interface.
My understanding is that it takes the file id, which would be https://www.openml.org/data/v1/get_csv/52214 but that yields "not found". Is there documentation for the CSV interface?

**Comment by joaquinvanschoren** [comment]
Fixed. This was a bug in the database.

@janvanrijn: the 'extension' field was missing for file 52214. There were many more of these. I updated the field with 'arff' if there file path indeed ended in '.arff'.

Your understanding of the get_csv call is correct.
@janvanrijn: I assume this is also what was agreed in earlier discussion?

There is no documentation yet. I need to set up an entire different Swagger file for this because it's a different endpoint. Or, we can just add a description to the wiki...

**Comment by amueller** [comment]
I don't think any features should be documented in the wiki only. Also, someone asked me at a conference a couple of days ago how we make sure scikit-learn has such awesome documentation. (part of) The answer is: we never ever merge any feature without extensive documentation.

Maybe we should have a documentation sprint, and maybe think about how to structure the docs before that (see #201). Every time I have to ask you about something, that's a failure in the docs. Imagine all the users that are not me and not as aggressive about bugging you.

**Comment by joaquinvanschoren** [comment]
Data API now documented:
https://www.openml.org/api_data_docs#!/data/get_download_id

@janvanrijn, please let me know if I missed anything.
@amueller Yes! I think we should really have regular documentation sprints and be more strict that new features are documented right away.

**Comment by amueller** [comment]
Awesome. I'm happy to pitch in to add to the docs. It's also important to think about the structure of the docs. It took me 3 minutes to find out how to reach the page you linked to from the main site. It's unclear what the distinction between file api documentation and api documentation is. (also the server just went down while I was trying to play with it?)

**Comment by amueller** [comment]
Closing this as the bug is fixed, documentation discussion should probably happen in https://github.com/openml/website/issues/201 ?
