### ISSUE TITLE
Cannot install "OpenML" package in Weka 3.8.1

### ISSUE THREAD

**Issue by Pearapon** [openml/OpenML#605]
I tried to install "OpenmlWeka package" in Weka 3.8.1. I got the following errors :

java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at weka.core.packageManagement.DefaultPackageManager.getPackageArchiveInfo(DefaultPackageManager.java:354)
	at weka.core.packageManagement.DefaultPackageManager.installPackageFromArchive(DefaultPackageManager.java:501)
	at weka.core.packageManagement.DefaultPackageManager.installPackageFromURL(DefaultPackageManager.java:769)
	at weka.core.packageManagement.DefaultPackageManager.installPackageFromRepository(DefaultPackageManager.java:753)
	at weka.core.WekaPackageManager.installPackageFromRepository(WekaPackageManager.java:2093)
	at weka.gui.PackageManager$InstallTask.doInBackground(PackageManager.java:1390)
	at weka.gui.PackageManager$InstallTask.doInBackground(PackageManager.java:867)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Please help.
Regards
Pearapon S.
Bangkok, Thailand

**Comment by joaquinvanschoren** [comment]
@Pearapon, can you download the zip manually and install it locally via the package manager?

@janvanrijn, @ArlindKadra can you find out what is causing it? Is it really a problem with WEKA or is there something weird with our .zip? Other packages seem to install with fewer issues.

Thanks!

**Comment by janvanrijn** [comment]
@Pearapon this is where you can find the zip:
https://github.com/openml/openml-weka/releases
Installing it manually should fix the problem, as @joaquinvanschoren pointed out. 

Unfortunately, I can't reproduce the error. I know this error has been the case a (long) while ago when it pointed to an out-dated URL. Could it be that your weka package list cache is out-dated?

**Comment by Pearapon** [comment]
Dear Janvanrijn,

 

             I tried to download this “openML-weka” and installed it manually using Weka Package Manager successfully. But it did not load inside Weka when it started. Please help.

 



 

Regards

Pearapon S.

Bangkok, Thailand

**Comment by joaquinvanschoren** [comment]
Did you read this?
https://github.com/openml/OpenML/wiki/Weka

Do you see 'OpenML Experimenter' under the 'Tools' menu after you restart WEKA?

**Comment by joaquinvanschoren** [comment]
@Pearapon It is issue now resolved?

**Comment by Pearapon** [comment]
Dear Joaquin,

 

             I am have installed “OpenML” with package manager of Weka already. But, the OpenML cannot be loaded according to this screen capture

 



 

Please help.

 

Regards

Pearapon S.

Bangkok, Thailand

**Comment by joaquinvanschoren** [comment]
@janvanrijn @ArlindKadra I took a closer look. Here's what I found:
* I can reproduce the ZipError in Weka 3.8.1. I also updated the package list cache, so that's not the problem. It tries to download OpenmlWeka 0.9.3, because 0.9.5 apparently requires Weka 3.9 for some reason?? If you look at the description: http://weka.sourceforge.net/packageMetaData/OpenmlWeka/0.9.3.html
It points to this url: http://www.openml.org/downloads/OpenmlWeka.zip
-> That's http, not https. After googling for "ZipError Weka package manager" I found that this is recurrent weka problem for any URL that includes a redirect. The OpenML server will redirect you from http to https. So that may be the problem. 

* Manually installing the zip in Weka 3.8.1 does NOT work. It _seems_ to work, but if you look in the wekafiles directory, OpenmlWeka isn't there. My guess is it checks the Description.props file, sees that it requires Weka 3.9, and just stops at that point. And yes, if you unzip the OpenmlWeka.zip file on the OpenML server it turns out to be version 0.9.5.

**Solution**: Update the description of 'OpenmlWeka 0.9.5' that it only requires Weka 3.8, not 3.9.

**Comment by joaquinvanschoren** [comment]
I checked, and simply changing the dependencies in 0.9.5 doesn't work.

I recovered the 0.9.3 version. You can find it where it should be:
https://www.openml.org/downloads/OpenmlWeka.zip

I installed this zip (manually) via the package editor of Weka 3.8.1 and that went fine. I also ran a small experiment to check: https://www.openml.org/r/8857837

**Final solution**: If we now also update the description of 0.9.3 to go to https instead of http, hopefully the ZipError will also go away.
@janvanrijn, who do we email about that?

**Comment by joaquinvanschoren** [comment]
Coming back to this, just updating the url to https doesn't help. It gets rid of the ziperror, and the installation happily proceeds, but the OpenML Experimenter window doesn't appear. The zipfile it downloads: https://www.openml.org/downloads/OpenmlWeka.zip
only seems to work for Weka 3.9. Not Weka 3.8. 

We may need to build a new release that works on Weka 3.8.

**Comment by janvanrijn** [comment]
(Restarting weka could help, if you didn't do so yet .. )

I think I made the package requirements explicit 3.9, don't remember why. We don't need to build a new release, but must update the description file. I would be comfortably doing so if we could verify this works. Is there any easy way of testing if this package works in eclipse with Weka? Haven't set it up so might take a while.

**Comment by joaquinvanschoren** [comment]
(Obviously, I did that...)

Are the package requirement inside the zip file? Because I installed the zip directly. Again, WEKA doesn't complain during the install, but the menu item doesn't appear.

For testing, just delete your ~/wekafiles folder, download and run weka 3.8 and install OpenML via the .zip file (or url).

**Comment by joaquinvanschoren** [comment]
The requirements are indeed in the .zip file. If I manually change the requirement it works fine.
That means changing ~/wekafiles/packages/OpenmlWeka/Description.props and replacing
Depends=weka (>= 3.9.0)
with
Depends=weka (>= 3.8.0)

**Comment by janvanrijn** [comment]
It would be really cool if we could reflect this in the unit tests ..

**Comment by janvanrijn** [comment]
I updated the ZIP file and contacted Mark and Eibe for changing their records. Please close once solved

**Comment by janvanrijn** [comment]
It seemed to work on my end. Please reopen if the problem persists.
