### ISSUE TITLE
Meta-features not computed on private datasets

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#762]
It seems that a more recent change in the API blocks the meta-feature extractor to compute meta-features for private datasets:
```
[21-06-2018 22:10:46] [OK] [Process Dataset] Processing dataset 358 on special request.
[21-06-2018 22:10:46] [OK] [Download] Start downloading dataset: 358
org.openml.apiconnector.io.ApiException: Unknown dataset
```
I did use an admin account to start the meta-feature extractor.

**Comment by janvanrijn** [comment]
Thanks for reporting this. Apparently, the data qualities function does not take into account admin users, which is a bug. I will push a fix to the development branch. 

> It seems that a more recent change in the API [...]

Unless you can point to the git commit that shows that it has worked before, I am pretty convinced that this is not due to any change in the API, but never worked, nor was properly tested.

**Comment by joaquinvanschoren** [comment]
Cool, thanks.
I thought it must be more recent because some meta-features were computed, probably by an older version of the meta-feature extractor. Could have been a long time ago, though.

**Comment by janvanrijn** [comment]
Let's keep open until unit tested

**Comment by janvanrijn** [comment]
The fix is in the development branch and unit tested by means of the java unit test framework
