### ISSUE TITLE
Test server dataset evaluation engine

### ISSUE THREAD

**Issue by mfeurer** [openml/OpenML#976]
There appears to be an issue with the test server evaluation engine. The previously evaluated datasets number 2 has an error now:

```bash
feurerm@mllap04:~/sync_dir/projects/openml/python$ curl https://test.openml.org/api/v1/xml/data/features/2
<oml:error xmlns:oml="http://openml.org/openml">
<oml:code>274</oml:code>
<oml:message>No features found. Additionally, dataset processed with error</oml:message>
</oml:error>
```

**Comment by mfeurer** [comment]
(BTW: this appears to make the Python unit tests fail)

**Comment by joaquinvanschoren** [comment]
I think this broke after the last evaluation engine update. The following happens when processing dataset 2:
```
[03-06-2019 17:22:14] [OK] [Process Dataset] Processing dataset 2 on special request.
[03-06-2019 17:22:15] [OK] [URL] HTTP request status code [200] URL [https://openml.tue.nl/data/v1/download/1666876/anneal.arff?api_key=5c4fef1424a7ff1d3cd33640bf90acb1]
[03-06-2019 17:22:15] [OK] [Process Dataset] Processing dataset 2 - obtaining features.
weka.core.UnassignedClassException: Class index is negative (not set)!
```

You can see it downloads dataset 'anneal' from openml.tue.nl. That is the old openml server, not the test server. On the test server, dataset 2 is kr-vs-kp: https://test.openml.org/d/2

It seems like the evaluation engine is simply trying to process the wrong file?

**Comment by joaquinvanschoren** [comment]
@janvanrijn: does this ring a bell?

**Comment by janvanrijn** [comment]
Yes, I was testing using this dataset to fix another issue. As a result, some database fields were accidentally still in the test setting. Should be fixed now.

**Comment by mfeurer** [comment]
The builds are passing, thanks a lot!
